version: "3"
services:
  kubertest:
    build: app
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      REDIS_ADDRESS: "redis"
      REDIS_PORT: 6379
      BASE_URL: $BASE_URL
      APP_ID: $APP_ID

  redis:
    image: redis:latest
    #ports:
      #- 6379:6379
