pipeline {
    agent any
    stages {
        stage('Test')
            agent {
                docker {
                    image 'node:14'
                }
            }
            steps {
                sh 'node --version'
            }
        }
        stage('Build Docker Image'){
            steps {
                echo 'Building Docker Images...'
            }
        }
        stage('Push to Artifactory'){
            steps {
                echo 'Pushing to artifactory...'
            }
        }
    }
}